loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  query_scheduler:
    max_outstanding_requests_per_tenant: 10000
singleBinary:
  replicas: 1
  persistence:
    size: 1Gi
  storageClass: do-block-storage
monitoring:
  selfMonitoring:
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false
gateway:
  enabled: true
test:
  enabled: false