apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-manager-ingress
  namespace: comrade-ho-chi-minh
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: user-manager-auth-secret
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
spec:
  ingressClassName: nginx
  rules:
  - host: "um.comrade-ho-chi-minh.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: user-manager-service
            port:
              number: 5000
