# Default values for telegram-bot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: paramas/comrade_ho_chi_minh
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

secret:
  name: app-secrets

service:
  ports:
    - port: 5000
      targetPort: healthcheck
  type: ClusterIP

ingress:
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: user-manager-auth-secret
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  ingressClassName: nginx
  host: comrade-ho-chi-minh.space
  service:
    name: user-manager
    port:
      number: 5000
  tls:
    hosts: comrade-ho-chi-minh.space
    secretName: user-manager-nikita-tls






