apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
  namespace: loki-stack-comrade-ho-chi-minh
spec:
    selector:
         app.kubernetes.io/name: grafana
    type: NodePort
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
          nodePort: 30037