apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: comrade-ho-chi-minh
spec:
    selector:
        app: postgres
    ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432