apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "telegram-bot.fullname" . }}
  labels:
    {{- include "telegram-bot.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.ingress.service.name }}
            port:
              number: {{ .Values.ingress.service.port.number }}
  tls:
  - hosts:
    - {{ .Values.ingress.tls.hosts}}
    secretName: {{ .Values.ingress.tls.secretName}}