apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rule-telegram-bot-for-ho-chi-minh
  namespace: comrade-ho-chi-minh
  labels:
    release: prometheus
spec:
  groups:
    - name: telegram.rules
      rules:
        - alert: AlertmanagerTelegramPodDownNikita
          expr: |
            (
              kube_pod_status_phase{namespace="comrade-ho-chi-minh", phase="Running", pod=~"telegramm.*"} < 1
            ) OR absent(
              kube_pod_status_phase{namespace="comrade-ho-chi-minh", phase="Running", pod=~"telegramm.*"}
            )
          for: 1m
          labels:
            severity: critical
        - alert: AlertmanagerTelegramPodDownZika
          expr: |
            (
            kube_pod_status_phase{namespace="comrade-chatgpt-bot", phase="Running", pod=~"telegram.*"} < 1
            ) OR absent(
            kube_pod_status_phase{namespace="comrade-chatgpt-bot", phase="Running", pod=~"telegram.*"}
            )
          for: 1m
          labels:
            severity: critical
