apiVersion: v1
kind: Service
metadata:
  name: {{ include "telegram-bot.fullname" . }}
  labels:
    {{- include "telegram-bot.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "telegram-bot.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port | default 8443 }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort | default webhook-port }}
      name: webhook-port
  type: {{ .Values.service.type  | default "ClusterIP" }}