apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "user-manager.fullname" . }}
  labels: 
    {{- include "user-manager.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: user-manager-auth-secret
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name:  {{ .Values.ingress.service.name }}
            port:
              number: {{ .Values.ingress.service.port.number }}
  tls:
  - hosts:
    - {{ .Values.ingress.tls.hosts}}
    secretName: {{ .Values.ingress.tls.secretName}}



          