{
 "title": "Loki Logs",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Data_source", "query": "loki" },
   {
    "name": "Stream_selector",
    "query": {}
   },
   { "name": "filter" },
   { "name": "logger", "query": "httpx,__main__,root" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Logs view", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Loki logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{filename=\"/logs/logfmter_bot.log\"} |= `$filter` | logfmt"
    }
   ]
  },
  {
   "title": "Count logs level",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(at) (count_over_time({filename=\"/logs/logfmter_bot.log\"} |= `$filter` | logfmt [$__auto]))"
    }
   ]
  },
  {
   "title": "Count logs level",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by(logger) (count_over_time({filename=\"/logs/logfmter_bot.log\"} |= `$filter` | logfmt [$__auto]))"
    }
   ]
  },
  {
   "title": "Logger view",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{filename=\"/logs/logfmter_bot.log\"} |= `$filter` | logfmt | logger = `$logger`"
    }
   ]
  },
  {
   "title": "Count log level",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(at) (count_over_time({filename=\"/logs/logfmter_bot.log\"} |= `$filter` | logfmt | at =~ \".+\"[$__auto]))"
    }
   ]
  }
 ]
}