clients:
  - url: http://loki-local:3100/loki/api/v1/push

scrape_configs:
  - job_name: telegram-bot
    static_configs:
    - targets:
        - localhost
      labels:
        job: telegram_bot
        __path__: /logs/logfmter_bot.log  # Change this to the path of your log files
    pipeline_stages:
      - logfmt:
          mapping:
            at: at
            process: process
            logger: logger
            msg: msg
      - labels:
          at:
          process:
          logger:
          msg: