# Default values for telegram-bot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: paramas/comrade_ho_chi_minh
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

secret:
  name: app-secrets

service:
  ports:
    - port:  8443
      targetPort: 8443
  type: ClusterIP

ingress:
  annotations:
    cert-manager.io/cluster-issuer: "cert-manager"
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  ingressClassName: nginx
  host: webhook-hochiminh.danilevich-it-school.com
  service:
    name: telegramm-bot-telegram-bot
    port:
      number:  8443
  tls:
    hosts:  webhook-hochiminh.danilevich-it-school.com
    secretName: telegram-bot-tls
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 500m
    memory: 256Mi

hpa:
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector:
  node.kubernetes.io/instance-type: t3.medium

serviceAccount:
  name: sa-comrade-ho-chi-minh-bot
  aws_role_arn: ""