# Default values for telegram-bot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: paramas/comrade_ho_chi_minh
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

secret:
  name: app-secrets

service:
  ports:
    - port: 8080
      targetPort: 80
  type: ClusterIP

ingress:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  ingressClassName: nginx
  host: webhook-hochiminh.danilevich-it-school.com
  service:
    name: telegramm-bot-telegram-bot
    port:
      number: 8080
  tls:
    hosts:  webhook-hochiminh.danilevich-it-school.com
    secretName: telegram-bot-tls
