databaseChangeLog:
  - changeSet:
      id: 1
      author: nikita
      changes:
        - createTable:
            tableName: allowed_users
            columns:
              - column:
                  name: user_id
                  type: INT
                  constraints:
                    primaryKey: true
                    nullable: false