version: "3.9"

volumes:
  logs_volume: {}
  images_volume: {}

services:
  telegram-bot:
    build:
      context: ./telegram_bot
    env_file:
      - ./telegram_bot/.env
    volumes:
      - logs_volume:/app/logs
      - images_volume:/app/images

  # http://loki-local:3100
  loki-local:
    image: grafana/loki:2.9.5
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml

  grafana:
      image: grafana/grafana:10.2.0
      ports:
        - "3000:3000"
      volumes:
        - ./grafana/provisioning:/etc/grafana/provisioning
      depends_on:
        - loki-local
      env_file:
        - ./grafana/.env

  promtail:
    image: grafana/promtail:2.9.3
    volumes:
      - logs_volume:/logs
      - ./promtail:/etc/promtail
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki-local