name: Pylint User Manager

on:
  push:
    paths:
      - 'comrade-chatgpt-bot-main/user_manager/**'

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
      working-directory: ./comrade-chatgpt-bot-main/user_manager

    - name: Analysing the code with pylint
      run: |
        pylint  --rcfile=./user_manager/.pylintrc ./user_manager
      working-directory: ./comrade-chatgpt-bot-main
