name: Telegram Bot Kubernetes

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'comrade-chatgpt-bot-main/liquibase/**'
      - 'comrade-chatgpt-bot-main/telegram_bot/**'

jobs:
  pylint_test_build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
      working-directory: ./comrade-chatgpt-bot-main/telegram_bot

    - name: Analysing the code with pylint
      run: |
        pylint --rcfile=./telegram_bot/.pylintrc ./telegram_bot
      working-directory: ./comrade-chatgpt-bot-main

    

    - name: Populate .env file
      run: |
        touch .env
        echo "${{ secrets.FULL_ENV }}" >> .env
      working-directory: ./comrade-chatgpt-bot-main/

    # - name: Run unit tests
    #   run: |
    #     docker compose run --build --rm telegram-bot python test_bot.py
    #   working-directory: ./comrade-chatgpt-bot-main/
    # отказываемся от unit test

    - name: Set commit hash
      run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build bot docker image
      run: docker build . --tag paramas/comrade_ho_chi_minh:telegram_bot_${{ env.COMMIT_HASH }}
      working-directory: ./comrade-chatgpt-bot-main/telegram_bot
    
    - name: Build liquibase docker image
      run: docker build . --tag paramas/comrade_ho_chi_minh:telegram_bot_liquibase_${{ env.COMMIT_HASH }}
      working-directory: ./comrade-chatgpt-bot-main/liquibase

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push the telegram docker image
      run: docker push paramas/comrade_ho_chi_minh:telegram_bot_${{ env.COMMIT_HASH }}

    - name: Push the liquibase docker image
      run: docker push paramas/comrade_ho_chi_minh:telegram_bot_liquibase_${{ env.COMMIT_HASH }}

    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v4
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ap-southeast-1

    - uses: azure/setup-kubectl@v3

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
        mkdir -p ~/.kube
        mv kubeconfig ~/.kube/config

    # - name: install-doctl
    #   uses: digitalocean/action-doctl@v2
    #   with:
    #     token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    # наше окружение это aws server

    - name: create profile
      run: |
        aws configure --profile study set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure --profile study set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure --profile study set region us-east-1

    - name: Update kubeconfig
      run: aws eks --profile study --region ap-southeast-1 update-kubeconfig --name study-cluster


    - name: helm upgrade --install
      run: |
        helm upgrade --install  --namespace comrade-ho-chi-minh telegramm-bot --set image.tag=${{ env.COMMIT_HASH }} ./telegram-bot      
      working-directory: ./comrade-chatgpt-bot-main/helm
