name: User Manager Kubernetes

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'comrade-chatgpt-bot-main/user_manager/**'

jobs:
  test_build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Populate .env file
      run: |
        touch .env
        echo "${{ secrets.FULL_ENV }}" >> .env
      working-directory: ./comrade-chatgpt-bot-main/

    - name: Run unit tests
      run: |
        docker compose up -d postgres
        docker compose up liquibase
        docker compose run --build --rm user-manager python test_user_manager.py
      working-directory: ./comrade-chatgpt-bot-main/

    - name: Set commit hash
      run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --tag paramas/comrade_ho_chi_minh:user_manager_${{ env.COMMIT_HASH }}
      working-directory: ./comrade-chatgpt-bot-main/user_manager

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push the Docker image
      run: docker push  paramas/comrade_ho_chi_minh:user_manager_${{ env.COMMIT_HASH }}

    - uses: azure/setup-kubectl@v3

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
        mkdir -p ~/.kube
        mv kubeconfig ~/.kube/config

    - name: install-doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
    - name: kubectl set image
      run: |
        helm upgrade --install  --namespace comrade-ho-chi-minh user-manager --set image.tag=${{ env.COMMIT_HASH }} ./user-manager 
      working-directory: ./comrade-chatgpt-bot-main/helm